# Generated by Django 5.0.6 on 2024-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="station_name",
            field=models.CharField(default="Unknown Station", max_length=255),
        ),
    ]
